version: "3"

volumes:
  react_build_volume: # Имя нашего общего volume

services:
  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - react_build_volume:/app/build # Мы используем volume здесь
    # После сборки React приложения контейнер уже не нужен, поэтому можем его завершить
    command: ["true"] # Это дефолтная команда, которая завершит контейнер после сборки

  express:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - react_build_volume:/usr/src/app/public # И тут мы также используем volume
    environment:
      - WWW=/usr/src/app/public # Передаем переменную окружения в контейнер
    ports:
      - "3000:3000"
    depends_on:
      - react

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Копирование конфиг. файла Nginx
  #     - ./nginx_certs:/etc/nginx/ssl # Монтируем volume с сертификатами
  #   ports:
  #     - "4080:80" # Проброс порта для HTTP
  #     - "4443:443" # Проброс порта для HTTPS
  #   depends_on:
  #     - express
  #   restart: always
