version: "3"

services:
  fastapi:
    build:
      context: ./FastApi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo

  mongo:
    image: mongo
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongodb_data_container:
