version: "3"

services:
  react:
    image: jedaiok/bx24_fastapi:react
    volumes:
      - react_build:/app/build # Мы используем volume здесь
    # После сборки React приложения контейнер уже не нужен, поэтому можем его завершить
    command: ["true"] # Это дефолтная команда, которая завершит контейнер после сборки
    environment:
      - API_URL=fastapi:8000

  fastapi:
    image: ./FastApi
    volumes:
      - react_build:/app/build # Мы используем volume здесь
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo

  mongo:
    image: mongo
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

networks:
  app_network:

volumes:
  react_build:
  mongodb_data_container:
